# Generated by Django 5.0.6 on 2024-05-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mail_id', models.EmailField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('mailing_address', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
